"use client";

import { ArrowRight, Coins, Layers3, TrendingUp, Wallet } from "lucide-react";
import { ISSUE_BY_ID } from "@/data/market-issues";
import { formatCoin, formatNumber, formatPercent } from "@/lib/format";
import { portfolioTotals } from "@/lib/market";
import type { MarketIssue, UserState } from "@/types";

export function Portfolio({ state, market, onMarket }: { state: UserState; market: MarketIssue[]; onMarket: () => void }) {
  const totals = portfolioTotals(state, market);
  const held = market.filter((issue) => state.holdings[issue.id].quantity > 0);
  return <div className="portfolio-layout"><div className="page-heading"><div><span className="section-kicker">YOUR NEWSPI ASSETS</span><h1>내 포트폴리오<span className="title-dot">.</span></h1><p>읽고 벌고 투자한 결과를 한눈에 확인하세요.</p></div><button className="outline-button" onClick={onMarket}>거래소로 이동 <ArrowRight size={16} /></button></div>
    <div className="portfolio-overview"><div className="portfolio-main glass-panel"><span className="portfolio-label"><Wallet size={17} /> TOTAL ASSETS</span><strong className="total-number">{formatCoin(totals.totalAssets)}</strong><span className="portfolio-small">현금 코인 + 보유 이슈 평가금액</span><div className="portfolio-bars"><span style={{ width: `${totals.totalAssets ? (state.coins / totals.totalAssets) * 100 : 100}%` }} /><span style={{ width: `${totals.totalAssets ? (totals.holdingsValue / totals.totalAssets) * 100 : 0}%` }} /></div><div className="bar-legend"><span><i className="cash-dot" /> 보유 코인 {formatCoin(state.coins)}</span><span><i className="asset-dot" /> 투자 평가 {formatCoin(totals.holdingsValue)}</span></div></div><div className="portfolio-side"><div className="mini-stat glass-panel"><span><Coins size={17} /> 보유 코인</span><strong>{formatCoin(state.coins)}</strong><small>거래 가능한 잔액</small></div><div className="mini-stat glass-panel"><span><TrendingUp size={17} /> 전체 투자 수익률</span><strong className={totals.returnPercent >= 0 ? "positive" : "negative"}>{formatPercent(totals.returnPercent)}</strong><small>보유 이슈 평가손익 {totals.unrealized >= 0 ? "+" : ""}{formatCoin(totals.unrealized)}</small></div></div></div>
    <div className="holdings-panel glass-panel"><div className="holdings-title"><div><span className="section-kicker">CURRENT HOLDINGS</span><h2>보유 이슈 <span>{held.length}</span></h2></div><Layers3 size={20} /></div>{held.length ? <div className="holdings-table"><div className="holdings-head"><span>이슈</span><span>보유</span><span>평균 매수가</span><span>현재가</span><span>평가금액</span><span>평가손익</span></div>{held.map((issue) => { const holding = state.holdings[issue.id]; const value = holding.quantity * issue.currentPrice; const pnl = value - holding.quantity * holding.averagePrice; return <div key={issue.id} className="holding-row"><span className="holding-name"><i style={{ background: ISSUE_BY_ID[issue.id].color }} />{issue.name}</span><span>{formatNumber(holding.quantity)}주</span><span>{formatCoin(holding.averagePrice)}</span><span>{formatCoin(issue.currentPrice)}</span><span>{formatCoin(value)}</span><strong className={pnl >= 0 ? "positive" : "negative"}>{pnl >= 0 ? "+" : ""}{formatCoin(pnl)}</strong></div>; })}</div> : <div className="empty-holdings"><Layers3 size={38} /><strong>아직 보유한 이슈가 없어요.</strong><p>뉴스 퀴즈로 코인을 모으고 첫 이슈를 매수해 보세요.</p><button className="primary-button" onClick={onMarket}>거래소 둘러보기 <ArrowRight size={16} /></button></div>}</div><p className="market-disclaimer">전체 투자 수익률은 현재 보유 이슈의 평가손익 기준입니다. 게임용 가상 데이터입니다.</p></div>;
}
